version: "2.1"

services:
  sonarr:
    image: ghcr.io/danimart1991/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    restart: always
    healthcheck:
      test: "curl -Lf http://localhost:8989 || exit 1"
    network_mode: bridge
    ports:
      - 8989:8989/tcp
    volumes:
      - /media/hdd14tb/tv:/tv
      - /docker/tmp/sonarr_config:/config
      - /docker/etc/sonarr_backups:/config/Backups
      - /media/hdd2/downloads:/downloads
    environment:
      - TZ=${DOCKER_TZ}
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
