version: "2.1"

services:
  sonarr:
    image: ghcr.io/jade-team/sonarr:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}sonarr
    hostname: sonarr
    restart: always
    network_mode: bridge
    ports:
      - 8989:8989/tcp
    volumes:
      - ${DOCKER_PATH_TV}:/tv:rw
      - ${DOCKER_PATH_TEMPORARY}/sonarr_config:/config:rw
      - ${DOCKER_PATH_PERSISTENT}/sonarr_backups:/config/Backups:rw
      - ${DOCKER_PATH_DOWNLOADS}:/downloads:rw
    environment:
      - TZ=${DOCKER_TZ}
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
