version: "2.1"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:14.3.9
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}qbittorrent
    hostname: qbittorrent
    healthcheck:
      test: "curl -Lf http://localhost:8085"
    restart: always
    network_mode: bridge
    ports:
      - 6881:6881/tcp
      - 8085:8085/tcp
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/qbittorrent_config:/config:rw
      - ${DOCKER_PATH_DOWNLOADS}:/downloads:rw
    environment:
      - TZ=${DOCKER_TZ}
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
      # optional. Only set if you don't want to use the default port 8080.
      - WEBUI_PORT=${DOCKER_QBITTORRENT_WEBUIPORT:-8085}
      # optional. Themes
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent
