version: "2"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    hostname: filebrowser
    restart: always
    network_mode: bridge
    ports:
      - 8086:80
    volumes:
      - /:/srv
      - ${DOCKER_PATH_PERSISTENT}/filebrowser_config/.filebrowser.json:/.filebrowser.json:rw
      - ${DOCKER_PATH_PERSISTENT}/filebrowser_config/database.db:/database.db:rw
    environment:
      - TZ=${DOCKER_TZ}
