version: "2"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    hostname: filebrowser
    restart: always
    network_mode: bridge
    ports:
      - 8086:80
    volumes:
      - /:/srv
      - /docker/etc/filebrowser_config/.filebrowser.json:/.filebrowser.json
      - /docker/etc/filebrowser_config/database.db:/database.db
    environment:
      - TZ=${DOCKER_TZ}
