version: '2'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: Filebrowser
    hostname: filebrowser
    restart: always
    network_mode: bridge
    ports:
      - 8086:80
    volumes:
      - /:/srv
      - /var/docker/filebrowser_config/database.db:/database.db
    env_file:
      - ../.env
      - ./.env