version: "2.1"

services:
  filebrowser:
    image: 	filebrowser/filebrowser:v2-s6
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}filebrowser
    hostname: filebrowser
    restart: always
    network_mode: bridge
    ports:
      - 8086:80
    volumes:
      - /:/srv
      - ${DOCKER_PATH_PERSISTENT}/filebrowser_config:/config:rw
      - ${DOCKER_PATH_PERSISTENT}/filebrowser_database:/database:rw
    environment:
      - PUID=${DOCKER_ROOTPUID:-0}
      - PGID=${DOCKER_ROOTPGID:-0}
      - TZ=${DOCKER_TZ}
