version: '2'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: Filebrowser
    hostname: filebrowser
    restart: always
    ports:
      - "8086:80"
    volumes:
      - /:/srv
    env_file:
      - ../.env
      - ./.env