version: "2.1"

services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati:latest
    container_name: duplicati
    hostname: duplicati
    restart: always
    network_mode: bridge
    ports:
      - 8200:8200
    volumes:
      - /docker/etc/duplicati_config:/config:rw
      - /docker/backups:/backups:rw
      - /docker/etc:/source:ro
    environment:
      # Recommendation: Duplicati needs root user to get access to all files
      - PUID=${DOCKER_ROOTPUID:-0}
      - PGID=${DOCKER_ROOTPGID:-0}
      - TZ=${DOCKER_TZ}
