version: "2.1"

services:
  duplicati:
    image: duplicati/duplicati:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}duplicati
    hostname: duplicati
    restart: always
    # Recommendation: Duplicati needs root user to get access to all files
    user: "${DOCKER_ROOTPUID:-0}:${DOCKER_ROOTPGID:-0}"
    network_mode: bridge
    ports:
      - 8200:8200
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/duplicati_data:/data:rw
      - /docker/backups:/backups:rw
      - ${DOCKER_PATH_PERSISTENT}:/source:ro
    environment:
      - TZ=${DOCKER_TZ}
