version: "2"

services:
  traextor:
    image: djarbz/traextor:latest
    container_name: traextor
    hostname: traextor
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.socket:/var/run/docker.socket:ro
      - ${DOCKER_PATH_TEMPORARY}/traextor_certs:/certs:rw
      # Depends on Traefik container for DNSSEC/SSL certificates
      - ${DOCKER_PATH_PERSISTENT}/traefik_data:/acme:ro
    environment:
      - TZ=${DOCKER_TZ}
      - ACME_FILE=${DOCKER_TRAEXTOR_ACMEFILE}
      - CERT_PATH=${DOCKER_TRAEXTOR_CERTPATH}
      - OUTPUT_DIR=${DOCKER_TRAEXTOR_OUTPUTDIR}
