version: "2"

services:
  traextor:
    image: djarbz/traextor:latest
    container_name: traextor
    hostname: traextor
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.socket:/var/run/docker.socket
      - /docker/tmp/traextor_certs:/certs
      # Depends on Traefik container for DNSSEC/SSL certificates
      - /docker/etc/traefik_data:/acme
    env_file:
      - ../.env
      - ./.env
