version: "2"

services:
  traextor:
    image: djarbz/traextor:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}traextor
    hostname: traextor
    restart: always
    network_mode: bridge
    volumes:
      - /var/run/docker.socket:/var/run/docker.socket:ro
      - ${DOCKER_PATH_TEMP}/traextor_certs:/certs:rw
      # Depends on Traefik container for DNSSEC/SSL certificates
      - ${DOCKER_PATH_ETC}/traefik_data:/acme:ro
    environment:
      - TZ=${DOCKER_TZ}
      - ACME_FILE=/acme/acme.json
      - CERT_PATH=/certs
      - OUTPUT_DIR=/certs
