version: "2"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    restart: always
    network_mode: bridge
    ports:
      - 443:443/tcp
      - 80:80/tcp
      - 8080:8080/tcp
    volumes:
      - /var/run/docker.socket:/var/run/docker.socket:ro
      - /docker/etc/traefik_data:/etc/traefik
      - /docker/tmp/traefik_log:/var/log/traefik
    env_file:
      - ../.env
      - ./.env
