version: "2"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    restart: always
    network_mode: bridge
    ports:
      - 443:443/tcp
      - 80:80/tcp
      - 8081:8080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_PATH_PERSISTENT}/traefik_data:/etc/traefik:rw
      # Must change logs folder. See tips in README.
      - ${DOCKER_PATH_TEMPORARY}/traefik_log:/var/log/traefik:rw
    environment:
      - TZ=${DOCKER_TZ}
      - AZURE_CLIENT_ID=${DOCKER_TRAEFIK_AZURECLIENTID}
      - AZURE_CLIENT_SECRET=${DOCKER_TRAEFIK_AZURECLIENTSECRET}
      - AZURE_ENVIRONMENT=${DOCKER_TRAEFIK_AZUREENVIRONMENT}
      - AZURE_RESOURCE_GROUP=${DOCKER_TRAEFIK_AZURERESOURCEGROUP}
      - AZURE_SUBSCRIPTION_ID=${DOCKER_TRAEFIK_AZURESUBSCRIPTIONID}
      - AZURE_TENANT_ID=${DOCKER_TRAEFIK_AZURETENANTID}
