version: "2.1"

services:
  radarr:
    image: ghcr.io/danimart1991/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: always
    healthcheck:
      test: "curl -Lf http://localhost:7878 || exit 1"
    network_mode: bridge
    ports:
      - 7878:7878/tcp
    volumes:
      - ${DOCKER_PATH_MOVIES}:/movies
      - ${DOCKER_PATH_TEMPORARY}/radarr_config:/config
      - ${DOCKER_PATH_PERSISTENT}/radarr_backups:/config/Backups
      - ${DOCKER_PATH_DOWNLOADS}:/downloads
    environment:
      - TZ=${DOCKER_TZ}
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
