version: "2.1"

services:
  radarr:
    image: ghcr.io/jade-team/radarr:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}radarr
    hostname: radarr
    restart: always
    healthcheck:
      test: "curl -Lf http://localhost:7878 || exit 1"
    network_mode: bridge
    ports:
      - 7878:7878/tcp
    volumes:
      - ${DOCKER_PATH_MOVIES}:/movies:rw
      - ${DOCKER_PATH_TEMPORARY}/radarr_config:/config:rw
      - ${DOCKER_PATH_PERSISTENT}/radarr_backups:/config/Backups:rw
      - ${DOCKER_PATH_DOWNLOADS}:/downloads:rw
    environment:
      - TZ=${DOCKER_TZ}
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
