version: "2.1"

services:
  home-assistant:
    image: homeassistant/home-assistant:stable
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}home-assistant
    hostname: home-assistant
    healthcheck:
      test: "curl -Lf http://localhost:8123 || exit 1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_PATH_PERSISTENT}/home-assistant_config:/config:rw
      - ${DOCKER_PATH_TEMPORARY}/home-assistant_tmp:/tmp:rw
    restart: always
    network_mode: host
    environment:
      - TZ=${DOCKER_TZ}
