version: "2.1"

services:
  ouroboros:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros
    hostname: ouroboros
    # Need if RUN_ONCE=true
    restart: "no"
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - TZ=${DOCKER_TZ}
      - CLEANUP=${DOCKER_OUROBOROS_CLEANUP:-false}
      - MONITOR=${DOCKER_OUROBOROS_MONITOR}
      - IGNORE=${DOCKER_OUROBOROS_IGNORE}
      # Notifications using apprise: https://github.com/pyouroboros/ouroboros/wiki/Notifications
      - NOTIFIERS=${DOCKER_OUROBOROS_NOTIFIERS}
      - LOG_LEVEL=${DOCKER_OUROBOROS_LOGLEVEL:-info}
      # Interval not used if Run Once is setted to true. I use Ouroboros with an external cron.
      - RUN_ONCE=${DOCKER_OUROBOROS_RUNONCE:-false}
      - SKIP_STARTUP_NOTIFICATIONS=${DOCKER_OUROBOROS_SKIPSTARTUPNOTIFICATIONS:-true}
      # More options and info in https://github.com/pyouroboros/ouroboros/wiki/Usage
