version: "2"

services:
  ouroboros:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros
    hostname: ouroboros
    # Need if RUN_ONCE=true
    restart: "no"
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ../.env
      - ./.env
