version: "2"

services:
  checkmk-raw:
    image: checkmk/check-mk-raw:2.2.0
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}checkmk-raw
    hostname: checkmk-raw
    restart: always
    # This overwrites image healthcheck. Default has too short timeout and sometimes fails.
    healthcheck:
      test: "omd status || exit 1"
      interval: 1m0s
      timeout: 30s
      retries: 3
      start_period: 0s
    network_mode: bridge
    ports:
      - 5000:5000
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/checkmk-raw_data:/omd/sites:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${DOCKER_TZ}
