version: "2.1"

services:
  jackett:
    image: ghcr.io/hotio/jackett:latest
    container_name: jackett
    hostname: jackett
    restart: always
    healthcheck:
      test: "curl -Lf http://localhost:9117 || exit 1"
    network_mode: bridge
    ports:
      - 9117:9117/tcp
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/jackett_config:/config
      # Comment to use original .yaml definitions
      - ${DOCKER_PATH_PERSISTENT}/jackett_definitions:/app/Definitions
    environment:
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
      - TZ=${DOCKER_TZ}
