version: "2.1"

services:
  jackett:
    image: ghcr.io/hotio/jackett:latest
    container_name: jackett
    hostname: jackett
    restart: always
    healthcheck:
      test: "curl -Lf http://localhost:9117 || exit 1"
    network_mode: bridge
    ports:
      - 9117:9117/tcp
    volumes:
      - /docker/etc/jackett_config:/config
      # Comment to use original .yaml definitions
      - /docker/etc/jackett_definitions:/app/Definitions
    env_file:
      - ../.env
      - ./.env
