version: "2"

services:
  azure-dns-updater:
    image: danimart1991/azure-dns-updater:latest
    container_name: azure-dns-updater
    hostname: azure-dns-updater
    restart: always
    network_mode: host
    env_file:
      - ../.env
      - ./.env
