version: "2"

services:
  debian-base:
    image: debian:11-slim
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}debian
    hostname: debian
    restart: "no"
    network_mode: bridge
    privileged: true
    volumes:
      - /bin/systemctl:/bin/systemctl:ro
      - /run/systemd/system:/run/systemd/system:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - TZ=${DOCKER_TZ}

  debian-reboot:
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}debian-reboot
    extends:
      service: debian-base
    command: systemctl reboot

  debian-shutdown:
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}debian-shutdown
    extends:
      service: debian-base
    command: systemctl shutdown
