version: "2"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    hostname: adguardhome
    command: --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -w /opt/adguardhome/work
    restart: always
    network_mode: host
    volumes:
      - ${DOCKER_PATH_TEMPORARY}/adguardhome_work:/opt/adguardhome/work:rw
      - ${DOCKER_PATH_PERSISTENT}/adguardhome_config:/opt/adguardhome/conf:rw
      # Depends on Traextor container for DNSSEC/SSL certificates
      - ${DOCKER_PATH_TEMPORARY}/traextor_certs:/opt/adguardhome/certs:ro
    environment:
      - TZ=${DOCKER_TZ}
