version: '2'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: Jellyfin
    hostname: jellyfin
    restart: always
    user: <PUID>:<PGID>
    network_mode: bridge
    ports:
      - 8096:8096/tcp
      - 1900:1900/udp # optional. Used for service auto-discovery
      - 7359:7359/udp # optional. Used for client auto-discovery
    volumes:
      - /var/docker/jellyfin_config:/config
      - /var/docker/jellyfin_cache:/cache
      - /media/hdd:/media
    # Transcoding using VAAPI
    # devices:
    #   - /dev/dri/card0:/dev/dri/card0
    #   - /dev/dri/renderD128:/dev/dri/renderD128
    env_file:
      - ../.env
      - ./.env