version: "2.1"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: always
    privileged: true
    healthcheck:
      test: "curl -Lf http://localhost:8096/health || exit 1"
    network_mode: bridge
    ports:
      - 8096:8096/tcp
      - 1900:1900/udp # optional. Used for service auto-discovery
      - 7359:7359/udp # optional. Used for client auto-discovery
    volumes:
      - /docker/etc/jellyfin_config:/config
      - /docker/tmp/jellyfin_cache:/cache
      - /media/hdd:/media
    # Transcoding using VAAPI (https://jellyfin.org/docs/general/server/transcoding.html)
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    env_file:
      - ../.env
      - ./.env
