version: "2.1"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: always
    privileged: true
    network_mode: bridge
    ports:
      - 8096:8096/tcp
      - 1900:1900/udp # optional. Used for service auto-discovery
      - 7359:7359/udp # optional. Used for client auto-discovery
    volumes:
      - /docker/etc/jellyfin_config:/config
      - /docker/tmp/jellyfin_cache:/cache
      - /media/hdd/movies:/media/movies
      - /media/hdd14tb/tv:/media/tv
    # optional. Transcoding using VAAPI (https://jellyfin.org/docs/general/server/transcoding.html)
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - JELLYFIN_PublishedServerUrl=${DOCKER_JELLYFIN_PUBLISHEDSERVERURL}
      # Moved Logs to another folder to avoid mix with configuration files
      - JELLYFIN_LOG_DIR=${DOCKER_JELLYFIN_LOGDIR}
      - TZ=${DOCKER_TZ}
