version: "2.1"

services:
  airdcpp-webclient:
    image: gangefors/airdcpp-webclient:latest
    container_name: airdcpp-webclient
    hostname: airdcpp-webclient
    restart: always
    network_mode: bridge
    ports:
      - 21248:21248/tcp
      - 21248:21248/udp
      - 21249:21249/tcp
      - 5600:5600/tcp
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/airdcpp-webclient_data:/airdcpp-webclient/config:rw
      # Must change default logs folder. See tips in README.
      - ${DOCKER_PATH_TEMPORARY}/airdcpp-webclient_logs:/airdcpp-webclient/logs:rw
      # Must change default downloads folder to /downloads.
      - ${DOCKER_PATH_DOWNLOADS}/airdcpp:/downloads:rw
      - ${DOCKER_PATH_MOVIES}:/movies:rw
      - ${DOCKER_PATH_TV}:/tv:rw
    environment:
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
      - TZ=${DOCKER_TZ}
