version: "2.1"

services:
  airdcpp-webclient:
    image: gangefors/airdcpp-webclient:latest
    container_name: airdcpp-webclient
    hostname: airdcpp-webclient
    restart: always
    network_mode: bridge
    ports:
      - 21248:21248/tcp
      - 21248:21248/udp
      - 21249:21249/tcp
      - 5600:5600/tcp
    volumes:
      - /docker/etc/airdcpp-webclient_data:/airdcpp-webclient/config
      # Must change default logs folder. See tips in README.
      - /docker/tmp/airdcpp-webclient_logs:/airdcpp-webclient/logs
      # Must change default downloads folder to /downloads.
      - /media/hdd2/downloads/airdcpp:/downloads
      - /media/hdd/movies:/movies
      - /media/hdd14tb/tv:/tv
    environment:
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
      - TZ=${DOCKER_TZ}
