version: "2.1"

services:
  node-red:
    image: nodered/node-red:latest-12
    container_name: node-red
    hostname: node-red
    restart: always
    network_mode: bridge
    ports:
      - 1880:1880/tcp
    # Needed to work with Docker Containers inside Node-RED
    group_add:
      - ${DOCKER_GID:-998}
    volumes:
      - /docker/etc/node-red_data:/data
      # Needed to work with Docker Containers inside Node-RED
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${DOCKER_TZ}
