version: "2.1"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}node-red
    hostname: node-red
    restart: always
    network_mode: bridge
    ports:
      - 1880:1880/tcp
    # Needed to work with Docker Containers inside Node-RED
    group_add:
      - ${DOCKER_GID:-998}
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/node-red_data:/data:rw
      # Needed to work with Docker Containers inside Node-RED
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - TZ=${DOCKER_TZ}
