version: '2'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: Portainer
    hostname: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    network_mode: bridge
    ports:
      - 9000:9000
      #- 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    env_file:
      - ../.env
      - ./.env

volumes:
  data: