version: "2.1"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}portainer
    hostname: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    network_mode: bridge
    ports:
      - 9000:9000
      #- 8000:8000 #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${DOCKER_PATH_PERSISTENT}/portainer_data:/data:rw
    environment:
      - TZ=${DOCKER_TZ}
