version: '3'

services:
  netdata:
    image: netdata/netdata
    restart: always
    container_name: Netdata
    hostname: netdata
    network_mode: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - cache:/var/cache/netdata
      - lib:/var/lib/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/host/etc/os-release:ro
    env_file:
      - ../.env
      - ./.env

volumes:
  cache:
  lib: