version: "2.1"

services:
  bazarr:
    image: cr.hotio.dev/hotio/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    restart: always
    healthcheck:
      test: "curl -Lf http://localhost:6767 || exit 1"
    network_mode: bridge
    ports:
      - 6767:6767/tcp
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/bazarr_config:/config:rw
      - ${DOCKER_PATH_MOVIES}:/movies:rw
      - ${DOCKER_PATH_TV}:/tv:rw
    environment:
      - TZ=${DOCKER_TZ}
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
