version: "2.1"

services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}unifi-controller
    hostname: unifi-controller
    restart: always
    network_mode: bridge
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      #- 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    volumes:
      - ${DOCKER_PATH_TEMPORARY}/unifi-controller_config:/config:rw
      - ${DOCKER_PATH_PERSISTENT}/unifi-controller_backup:/config/data/backup:rw
    environment:
      - TZ=${DOCKER_TZ}
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
