version: "2"

services:
  jackett2telegram:
    image: danimart1991/jackett2telegram:latest
    container_name: jackett2telegram
    hostname: jackett2telegram
    restart: always
    network_mode: host
    volumes:
      - /docker/etc/jackett2telegram_config:/app/config
      - /media/hdd2/downloads/blackhole:/app/blackhole
    env_file:
      - ../.env
      - ./.env
