version: "2.1"

services:
  jackett2telegram:
    image: danimart1991/jackett2telegram:latest
    container_name: jackett2telegram
    hostname: jackett2telegram
    restart: always
    network_mode: host
    volumes:
      - /docker/etc/jackett2telegram_config:/app/config
      - /media/hdd2/downloads/blackhole:/app/blackhole
    environment:
      - CHATID=${DOCKER_JACKETT2TELEGRAM_CHATID}
      - TOKEN=${DOCKER_JACKETT2TELEGRAM_TOKEN}
      - DELAY=${DOCKER_JACKETT2TELEGRAM_DELAY:-60}
      - LOG_LEVEL=${DOCKER_JACKETT2TELEGRAM_LOGLEVEL:-WARNING}
      - TZ=${DOCKER_TZ}
