version: "2.4"

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}freshrss
    hostname: freshrssred
    restart: always
    network_mode: bridge
    ports:
      - 8082:80/tcp
    volumes:
      - ${DOCKER_PATH_ETC}/freshrss_data:/var/www/FreshRSS/data
      - ${DOCKER_PATH_ETC}/freshrss_extensions:/var/www/FreshRSS/extensions
    logging:
      options:
        max-size: 10m
    environment:
      - TZ=${DOCKER_TZ}
      - CRON_MIN="00,30"
