version: "2.1"

services:
  esphome:
    image: esphome/esphome:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}esphome
    hostname: esphome
    restart: always
    healthcheck:
      test: "curl -Lk -fsS http://localhost:6052/version || exit 1"
    network_mode: host
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_PATH_VAR}/esphome_config:/config:rw
    environment:
      # Use ICMP pings to check the status of the device if mDNS to show online/offline state in the dashboard fails
      # https://github.com/esphome/issues/issues/641#issuecomment-534156628
      - ESPHOME_DASHBOARD_USE_PING=${DOCKER_ESPHOME_DASHBOARDUSEPING:-false}
      - USERNAME=${DOCKER_ESPHOME_USERNAME}
      - PASSWORD=${DOCKER_ESPHOME_PASSWORD}
      - TZ=${DOCKER_TZ}
