version: "2.1"

services:
  esphome:
    image: esphome/esphome:latest
    container_name: esphome
    hostname: esphome
    restart: always
    network_mode: bridge
    ports:
      - 6052:6052
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/tmp/esphome_config:/config:rw
    environment:
      # Use ICMP pings to check the status of the device if mDNS to show online/offline state in the dashboard fails
      # https://github.com/esphome/issues/issues/641#issuecomment-534156628
      - ESPHOME_DASHBOARD_USE_PING=${DOCKER_ESPHOME_DASHBOARDUSEPING:-false}
      - USERNAME=${DOCKER_ESPHOME_USERNAME}
      - PASSWORD=${DOCKER_ESPHOME_PASSWORD}
      - TZ=${DOCKER_TZ}
