version: '2'

services:
  esphome:
    image: esphome/esphome:latest
    container_name: ESPHome
    hostname: esphome
    restart: always
    network_mode: bridge
    ports:
      - 6052:6052
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/docker/esphome_config:/config:rw
    env_file:
      - ../.env
      - ./.env