version: "2"

services:
  autoremove-torrents:
    image: dantebarba/autoremove-torrents:1.7.1
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}autoremove-torrents
    hostname: autoremove-torrents
    restart: always
    network_mode: bridge
    volumes:
      - ${DOCKER_PATH_ETC}/autoremove-torrents_config/config.yml:/app/config.yml:ro
      # Empty autoremove-torrents.log file must be created previously on host
      - ${DOCKER_PATH_LOGS}/autoremove-torrents_log/autoremove-torrents.log:/var/log/autoremove-torrents.log:rw
    environment:
      - TZ=${DOCKER_TZ}
