version: "2"

services:
  nut-upsd:
    image: upshift/nut-upsd:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}nut-upsd
    hostname: nut-upsd
    restart: always
    network_mode: bridge
    ports:
      - 3493:3493/tcp
    devices:
      - /dev/bus/usb/002/002:/dev/bus/usb/002/002
    environment:
      - API_USER=${DOCKER_NUTUPSD_API_USER}
      - API_PASSWORD=${DOCKER_NUTUPSD_API_PASSWORD}
      - ADMIN_PASSWORD=${DOCKER_NUTUPSD_ADMIN_PASSWORD}
      - UPS_NAME=${DOCKER_NUTUPSD_UPS_NAME}
      - UPS_DESC=${DOCKER_NUTUPSD_UPS_DESC}
      - UPS_DRIVER=${DOCKER_NUTUPSD_UPS_DRIVER}
      - UPS_PORT=${DOCKER_NUTUPSD_UPS_PORT}
      - SHUTDOWN_CMD=${DOCKER_NUTUPSD_SHUTDOWN_CMD}
      - TZ=${DOCKER_TZ}
